<a href="https://colab.research.google.com/github/sami01979/dataframe_in_panda/blob/main/merging_joining_concatanation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [8]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4],
    'name':['Bob','Jake','Lisa','Sue'],
    'group':['Accounting','Engineering','Engineering','HR']
})
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,5,4],
    'salary':[70000,80000,120000,90000,56000,23000],
    'bonus':[1000,2000,3000,4000,2000,9000]

})

In [3]:
employees

   employee_id  name        group
0            1   Bob   Accounting
1            2  Jake  Engineering
2            3  Lisa  Engineering
3            4   Sue           HR

In [4]:
salaries

   employee_id  salary  bonus
0            1   70000   1000
1            2   80000   2000
2            3  120000   3000
3            4   90000   4000

In [9]:
pd.merge(employees,salaries)

   employee_id  name        group  salary  bonus
0            1   Bob   Accounting   70000   1000
1            2  Jake  Engineering   80000   2000
2            3  Lisa  Engineering  120000   3000
3            4   Sue           HR   23000   9000

In [12]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id  name        group  salary  bonus
0            1   Bob   Accounting   70000   1000
1            2  Jake  Engineering   80000   2000
2            3  Lisa  Engineering  120000   3000
3            4   Sue           HR   23000   9000
4            5   NaN          NaN   56000   2000
5            6   NaN          NaN   90000   4000

Concatenation

In [13]:
df1=pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3']
})
df2=pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7']
})

In [15]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [16]:
df2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7