<a href="https://colab.research.google.com/github/sami01979/dataframe_in_panda/blob/main/panda_missingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [13]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[5,np.nan,7,np.nan,6],
    'C':[np.nan,np.nan,11,12,np.nan],
    'D':[13,14,np.nan,np.nan,17]
}
df=pd.DataFrame(data)
df

     A    B     C     D
0  1.0  5.0   NaN  13.0
1  2.0  NaN   NaN  14.0
2  NaN  7.0  11.0   NaN
3  4.0  NaN  12.0   NaN
4  5.0  6.0   NaN  17.0

In [3]:
df.isna()

       A      B      C
0  False  False   True
1  False   True   True
2   True  False  False
3  False   True  False

In [4]:
df.isna().sum()

A    1
B    2
C    2
dtype: int64

In [9]:
df.isna().any()

A    True
B    True
C    True
dtype: bool

Removing the data

In [14]:
df.dropna(thresh=3)

     A    B   C     D
0  1.0  5.0 NaN  13.0
4  5.0  6.0 NaN  17.0

Filling the missing data

In [15]:
df.fillna(0)

     A    B     C     D
0  1.0  5.0   0.0  13.0
1  2.0  0.0   0.0  14.0
2  0.0  7.0  11.0   0.0
3  4.0  0.0  12.0   0.0
4  5.0  6.0   0.0  17.0

In [16]:
values={'A':11,'B':22,'C':33,'D':44}
df.fillna(value=values)

      A     B     C     D
0   1.0   5.0  33.0  13.0
1   2.0  22.0  33.0  14.0
2  11.0   7.0  11.0  44.0
3   4.0  22.0  12.0  44.0
4   5.0   6.0  33.0  17.0

In [17]:
df.fillna(df.mean)

,A,B,C,D
0,1.0,5.0,<bound method DataFrame.mean of A B ...,13.0
1,2.0,<bound method DataFrame.mean of A B ...,<bound method DataFrame.mean of A B ...,14.0
2,<bound method DataFrame.mean of A B ...,7.0,11.0,<bound method DataFrame.mean of A B ...
3,4.0,<bound method DataFrame.mean of A B ...,12.0,<bound method DataFrame.mean of A B ...
4,5.0,6.0,<bound method DataFrame.mean of A B ...,17.0